### ISSUE TITLE
Allow easier distinguishing between rss- and non-rss scrapers

### ISSUE THREAD

**Issue by damian0604** [uvacw/inca#275]
When running inca in the preferred way, `myinca=inca.Inca()`, it's a nice feature that `myinca.scrapers` automatically contains all scrapers. However, it would be good if we could distinguish between scrapers that have to run periodically (especially RSS-scrapers) and scrapers that have to be run basically once (e.g., to scrape a whole forum).

That would  allow us to write a helper script (used by a cronjob) that loops over all RSS-feeds and scraps them (we now have a manually compiled list of these scrapers in production).

@bobvdvelde do you have an idea of what would be the preferred way to achieve this?

**Comment by bobvdvelde** [comment]
Yes, I believe we should move rss-scrapers to another folder (e.g. `inca/rss` instead of `inca/scrapers`). We can then modify the `Inca` object to have both `inca.scrapers` and `inca.rss` methods. 

Alternatively, we could ad `_rss` endings to rss-scraper names, without moving them to their own category.

**Comment by damian0604** [comment]
code is written and works, i'll make a PR once we characterized and sorted the scrapers in corresponding folders (thanks in advance to @annekroon)

**Comment by damian0604** [comment]
Solved by PR #277
