### ISSUE TITLE
German newspaper: Die Welt

### ISSUE THREAD

**Issue by bobvdvelde** [uvacw/inca#64]
Die Welt can be found at https://www.welt.de/

**Comment by arno12** [comment]
What's the best way to deal with video articles? So far, I'm returning date, title, author but there is usually no text.

**Comment by damian0604** [comment]
That's a good point and should be addressed more generally. Simply leaving the text empy doesn't seem like the best solution to me, because many users will assume that the empty text means that there was an error or something. I see two possible solutions.
- Return a text field containing something like "[this article contains only a video]"
- or: we change the api in such a way that scrapers also return a field that might be called 'type' which can have 'text', 'video', 'audio', ... etc as values.
I think I'd have a preference for the latter (the first is a bit like a dirty workaround...), but it would require some more changes elsewhere in the code.
@bobvdvelde , what's your take on this?

**Comment by bobvdvelde** [comment]
The most easy and intuitive solution to me appears to be the inclusion of an empty text field {'text': ''}, although this may be confused with erroneous parsing of the HTML. 

We can either opt to include a 'meta' language with things such as 'MISSING', 'PARSE ERROR' etcetera, but this would require consistent implementation throughout the scrapers (another part of the learning curve for new contributors).
