### ISSUE TITLE
Sentiment analysis

### ISSUE THREAD

**Issue by theoaraujo** [uvacw/inca#90]
PersCom: Hanneke: Automatic coding/help with coding this content. Things that could be coded automatically are likes/comments/tone of comments

**Comment by damian0604** [comment]
First sentiment analysis is implemented (PR #182) . It's english-language sentiment analysis based on the Vader algorithm.
algorithms for other languages (like Sentistrength and/or pattern) still have to be added, but that's non-trivial due to non-availability for Py3

**Comment by annekroon** [comment]
Closing this issue for now, because 
- English-language sentiment analysis is included now as per PR #182 
- we agreed to use Py3 (thus, pattern is no option, unless put in a container or sth.)
- Sentistrength is not open Source.
Thus, no sentiment analysis for Dutch texts right now (people can still do this locally of course). We can re-open the issue once a suitable package becomes available.
